CREATE TABLE codigo_postal_madrid (
    codigo VARCHAR(5) PRIMARY KEY,
    nombre VARCHAR(100),
    direccion VARCHAR(255),
    horario VARCHAR(100)
);

INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28001', 'Local en Gran VÃ­a', 'Gran VÃ­a, 19', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28002', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 9', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28003', 'Local en Calle de Fuencarral', 'Calle de Fuencarral, 22', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28004', 'Local en Calle de Fuencarral', 'Calle de Fuencarral, 84', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28005', 'Local en Calle de Serrano', 'Calle de Serrano, 65', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28006', 'Local en Avenida de AmÃ©rica', 'Avenida de AmÃ©rica, 57', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28007', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 96', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28008', 'Local en Calle del Arenal', 'Calle del Arenal, 80', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28009', 'Local en Calle de Hortaleza', 'Calle de Hortaleza, 66', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28010', 'Local en Calle de AlcalÃ¡', 'Calle de AlcalÃ¡, 2', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28011', 'Local en Calle Mayor', 'Calle Mayor, 51', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28012', 'Local en Calle de Hortaleza', 'Calle de Hortaleza, 47', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28013', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 52', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28014', 'Local en Calle del Arenal', 'Calle del Arenal, 65', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28015', 'Local en Calle de Fuencarral', 'Calle de Fuencarral, 4', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28016', 'Local en Calle de Hortaleza', 'Calle de Hortaleza, 11', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28017', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 34', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28018', 'Local en Calle del Arenal', 'Calle del Arenal, 47', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28019', 'Local en Calle de Hortaleza', 'Calle de Hortaleza, 97', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28020', 'Local en Calle de Fuencarral', 'Calle de Fuencarral, 42', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28021', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 41', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28022', 'Local en Paseo del Prado', 'Paseo del Prado, 51', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28023', 'Local en Gran VÃ­a', 'Gran VÃ­a, 56', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28024', 'Local en Calle de AlcalÃ¡', 'Calle de AlcalÃ¡, 31', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28025', 'Local en Calle de Hortaleza', 'Calle de Hortaleza, 43', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28026', 'Local en Calle Mayor', 'Calle Mayor, 87', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28027', 'Local en Avenida de AmÃ©rica', 'Avenida de AmÃ©rica, 70', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28028', 'Local en Calle de Serrano', 'Calle de Serrano, 97', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28029', 'Local en Paseo del Prado', 'Paseo del Prado, 98', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28030', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 42', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28031', 'Local en Calle de Hortaleza', 'Calle de Hortaleza, 25', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28032', 'Local en Calle Mayor', 'Calle Mayor, 65', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28033', 'Local en Avenida de AmÃ©rica', 'Avenida de AmÃ©rica, 15', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28034', 'Local en Paseo del Prado', 'Paseo del Prado, 21', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28035', 'Local en Calle de Hortaleza', 'Calle de Hortaleza, 99', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28036', 'Local en Calle de Hortaleza', 'Calle de Hortaleza, 57', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28037', 'Local en Calle de Serrano', 'Calle de Serrano, 80', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28038', 'Local en Calle del Arenal', 'Calle del Arenal, 44', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28039', 'Local en Calle de Fuencarral', 'Calle de Fuencarral, 39', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28040', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 57', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28041', 'Local en Calle de Serrano', 'Calle de Serrano, 48', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28042', 'Local en Paseo del Prado', 'Paseo del Prado, 32', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28043', 'Local en Calle Mayor', 'Calle Mayor, 91', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28044', 'Local en Avenida de AmÃ©rica', 'Avenida de AmÃ©rica, 12', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28045', 'Local en Calle del Arenal', 'Calle del Arenal, 49', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28046', 'Local en Paseo del Prado', 'Paseo del Prado, 70', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28047', 'Local en Calle Mayor', 'Calle Mayor, 92', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28048', 'Local en Gran VÃ­a', 'Gran VÃ­a, 96', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28049', 'Local en Calle de Hortaleza', 'Calle de Hortaleza, 37', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28050', 'Local en Gran VÃ­a', 'Gran VÃ­a, 61', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28051', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 42', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28052', 'Local en Calle de AlcalÃ¡', 'Calle de AlcalÃ¡, 44', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28053', 'Local en Avenida de AmÃ©rica', 'Avenida de AmÃ©rica, 9', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28054', 'Local en Avenida de AmÃ©rica', 'Avenida de AmÃ©rica, 41', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28055', 'Local en Gran VÃ­a', 'Gran VÃ­a, 10', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28056', 'Local en Calle del Arenal', 'Calle del Arenal, 41', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28057', 'Local en Avenida de AmÃ©rica', 'Avenida de AmÃ©rica, 63', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28058', 'Local en Calle de Fuencarral', 'Calle de Fuencarral, 85', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28059', 'Local en Calle de AlcalÃ¡', 'Calle de AlcalÃ¡, 53', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28060', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 21', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28061', 'Local en Calle Mayor', 'Calle Mayor, 8', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28062', 'Local en Calle del Arenal', 'Calle del Arenal, 59', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28063', 'Local en Calle de Fuencarral', 'Calle de Fuencarral, 38', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28064', 'Local en Avenida de AmÃ©rica', 'Avenida de AmÃ©rica, 47', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28065', 'Local en Calle de Hortaleza', 'Calle de Hortaleza, 52', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28066', 'Local en Calle del Arenal', 'Calle del Arenal, 56', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28067', 'Local en Gran VÃ­a', 'Gran VÃ­a, 37', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28068', 'Local en Avenida de AmÃ©rica', 'Avenida de AmÃ©rica, 41', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28069', 'Local en Gran VÃ­a', 'Gran VÃ­a, 60', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28070', 'Local en Paseo del Prado', 'Paseo del Prado, 91', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28071', 'Local en Gran VÃ­a', 'Gran VÃ­a, 85', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28072', 'Local en Gran VÃ­a', 'Gran VÃ­a, 5', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28073', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 64', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28074', 'Local en Calle de Serrano', 'Calle de Serrano, 52', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28075', 'Local en Calle de Fuencarral', 'Calle de Fuencarral, 40', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28076', 'Local en Calle de Serrano', 'Calle de Serrano, 83', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28077', 'Local en Gran VÃ­a', 'Gran VÃ­a, 17', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28078', 'Local en Gran VÃ­a', 'Gran VÃ­a, 56', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28079', 'Local en Calle de Serrano', 'Calle de Serrano, 2', 'Lunes a Viernes de 10:00 a 16:00');
INSERT INTO codigo_postal_madrid (codigo, nombre, direccion, horario) VALUES ('28080', 'Local en Paseo de la Castellana', 'Paseo de la Castellana, 44', 'Lunes a Viernes de 10:00 a 16:00');